### ISSUE TITLE
Brand Name won't stick.  everytime I enter it, it says successful but nothing shows

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSend#10]
![image](https://user-images.githubusercontent.com/3675043/39002695-1b0d51aa-43c7-11e8-8d46-35ed31291ef9.png)

after saving and refeshing, it goes back to being blank

![image](https://user-images.githubusercontent.com/3675043/39002730-2d75f496-43c7-11e8-8acd-35a44e8b1679.png)

**Comment by bluenevus** [comment]
I created an admin account with your saverman gmail.  login with that

don't put passwords here.  this is a public site

**Comment by bluenevus** [comment]
take a look.  its blank.  even though the brand says microhealth on the website

![image](https://user-images.githubusercontent.com/3675043/39053691-a019c4d0-447d-11e8-82c4-accf7cc1a38e.png)

**Comment by bluenevus** [comment]
but no brand here in the upper right hand corner

![image](https://user-images.githubusercontent.com/3675043/39053902-37163382-447e-11e8-9369-7aaea3df51fd.png)

**Comment by ranjitpillai** [comment]
Brand name showing on upper left hand corner fixed.

**Comment by bluenevus** [comment]
still doesn't work.  see here

![screenshot 2018-04-21 at 3 34 44 pm](https://user-images.githubusercontent.com/3675043/39088056-b87b83fe-4579-11e8-9e1c-4909395e94cc.png)

after clicking change name, screen refreshed and here

![screenshot 2018-04-21 at 3 34 53 pm](https://user-images.githubusercontent.com/3675043/39088057-bb1ef4ce-4579-11e8-9b2e-88562e075796.png)
