### ISSUE TITLE
User may not edit their own Account by clicking the Edit button on the users-edit screen

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSend#104]
Edit user account button click did not display Edit User Account form, so user may not edit their own account. Yet, another user can edit another user's account.

Screenshot Example

![edit_user_btn_should_display_edit_user_account](https://user-images.githubusercontent.com/11938477/47933930-536a0b80-deac-11e8-9a26-84e7def941ab.jpg)

**Comment by bluenevus** [comment]
well I think its for security reasons.  People can't change their own role.  that would be dangerous

people can't change if they are active or not.  that is an admin function

However, I don't see any harm in people changing their own notification though I would prefer that to remain an admin function as long as that option is checked by default which is a must as it frustrated us for months trying to figure out why users don't get emails

--
Dr. Frank Tucker
CEO
MicroHealth, LLC
People * Value * Innovation

O: (855) 294-3547 |  F: (855)-850-1264
Address:  8245 Boone Blvd, Suite 706  |  Vienna, VA 22182
<http://www.microhealthonline.com/>Email: frank.tucker@microhealthllc.com<mailto:frank.tucker@microhealthllc.com>
www.microhealthllc.com<http://www.microhealthllc.com/>

www.microhealthllc.com<http://www.microhealthllc.com/>

________________________________
