### ISSUE TITLE
Add system user form - Notify new uploads by email should be checked by default

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSend#105]
Screenshot Example

![new_system_user_notify_email_default](https://user-images.githubusercontent.com/11938477/47935155-cc1e9700-deaf-11e8-8fed-369d43a5b4ef.jpg)

**Comment by ranjitpillai** [comment]
By default while adding new user "Notify new uploads by email" will be checked. For existing user I have marked manually.
