### ISSUE TITLE
Remove Orphan Files section from Draft Files screen

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSend#106]
Screenshot Example

![draft_files_screen_with_orphan_files](https://user-images.githubusercontent.com/11938477/48014790-7d623e80-e0f5-11e8-8a42-3a1c73d0cbe8.jpg)

**Comment by bluenevus** [comment]
Draft screen should have only one table for files were uploaded but not sent and it should simply be called draft.  Its for that user and only that user’s uploaded file that wasn’t sent

--- vr, Frank
