### ISSUE TITLE
Uploaded files should ONLY display under the user's Inbox, NOT my_files

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSend#113]
Uploaded files, whether as Client or as Group, should display under the user's Inbox screen, not "my_files". 

Screenshot Example

![my_files_should_not_display_all_inbox](https://user-images.githubusercontent.com/11938477/48157745-788cbe80-e29e-11e8-90b0-4b7d75234c04.jpg)

**Comment by LAlexMHllc** [comment]
This includes files uploaded for Clients Organizations and Users Organizations

**Comment by bluenevus** [comment]
there shouldn't be a my files.  it should be inbox and all files recieved should show in their inbox.  lets keep this simple

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by LAlexMHllc** [comment]
Only Admin should be able to view my_files by clicking a View as client button on the Clients Administration screen (Manage Clients folder; clients.php)

**Comment by ranjitpillai** [comment]
there shouldn't be my_files section for user's/client, it will redirect to inbox , also fixed the listing of client organization files in the inbox section.
