### ISSUE TITLE
Draft screen should have only one table for files were uploaded but not sent and it should simply be called draft.  Its for that user and only that user’s uploaded file that wasn’t sent

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSend#119]
Draft screen should have only one table for files were uploaded but not sent and it should simply be called draft.  Its for that user and only that user’s uploaded file that wasn’t sent. NOt a table above for orphan and another one for draft.  both of these files are indeed orphan but for the user...its draft so just have one table with drafts as the two are confusing

![image](https://user-images.githubusercontent.com/3675043/48499348-3d424080-e806-11e8-88db-fc44276f194e.png)

**Comment by LAlexMHllc** [comment]
For orphan files on Draft Files screen:

Date = Last Modified date or today date
Ext = get ext of file uploaded
Title = File Name; links to page to continue upload process
Size = File Size
Uploader = user
Sent to is blank
Assigned = No
Public = Private
Expiry = default expire date
Total downloads = 0
Action Edit button links to page to continue upload process
