### ISSUE TITLE
Email notification message displays whether email sent now, later, or not at all. Should message be removed?

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSend#147]
Not all uploaded files will receive an email notification immediately, or possibly not at all. Should the message be removed?

Screenshot Example

![upload_process_email_notification_message](https://user-images.githubusercontent.com/11938477/49241482-f5124900-f3d5-11e8-9aa0-a5355b1c1c29.jpg)

**Comment by bluenevus** [comment]
yes
