### ISSUE TITLE
Should this Organization Request screen be removed?

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSend#151]
Screenshot Example

![organizationrequest](https://user-images.githubusercontent.com/11938477/49306825-581ce200-f4a1-11e8-9fbc-cbf26ccd600e.jpg)

**Comment by LAlexMHllc** [comment]
Is Guest Drop-off Request supposed to display on this screen? See Issue #136

**Comment by bluenevus** [comment]
yes
