### ISSUE TITLE
A user should not be able to edit a file not uploaded by them

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSend#165]
"Uploader" should not have link to edit file if user is not uploader

Screenshot Example

![edit_file_link_only_uploader](https://user-images.githubusercontent.com/11938477/49528986-131ef400-f883-11e8-946b-b50c021d1060.jpg)

**Comment by bluenevus** [comment]
Is it because I’m an admin?

--- vr, Frank

**Comment by LAlexMHllc** [comment]
See Public Files for example
