### ISSUE TITLE
Guest Drop-off Summary screen - validate file was selected to upload on Submit to avoid error screen display

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSend#192]
Screenshot Example

![guest_drop_off_summary_make_sure_file_was_selected](https://user-images.githubusercontent.com/11938477/49824989-58469880-fd51-11e8-9cc3-796f09b4011a.jpg)

**Comment by ranjitpillai** [comment]
Fixed. Please check the issue #193
