### ISSUE TITLE
Disable / Enable Download/Upload file ?

### ISSUE THREAD

**Issue by cloudwaves** [MicroHealthLLC/mSend#264]
Hi, Do you have option to disable/enable the download / upload a file in User Group?
This will enable some security level to upload / download a file on user level.

**Comment by bluenevus** [comment]
Updated user install instructions.  This should clear up.  If you are on centos.  Just copy and paste the instructions.  If you are on Debian based, you will have to replace yum with apt-get and some things don’t apply like epel.  You don’t need the repo

--- vr, Frank

**Comment by bluenevus** [comment]
Working on it now.  We had this error once before about a year ago.

--- vr, Frank

**Comment by cloudwaves** [comment]
I found something...
 mSend/install/database.php
39.  `prev_assign` ENUM(\'0\',\'1\') NOT NULL DEFAULT \'0\',
40.  `prev_assign` ENUM(\'0\',\'1\') NOT NULL DEFAULT \'0\',

I have removed line 40 and tried installing... it got installed successfully. But the front login page is not working! I can see only blank page.

**Comment by cloudwaves** [comment]
I have an IP address and trying to access http://IPADDRESS/mSend
It gives me blank page.

**Comment by cloudwaves** [comment]
yeah... I just reinstalled in the root folder... /var/www/html/
configured the mSend from http://IPADDRESS/install
Configuration was success
Login page is blank still when accessing http://IPADDRESS/
having access to apache:apache to /var/www/html/* and /var/www/html
having 755 access to /var/www/html/* and /var/www/html

**Comment by bluenevus** [comment]
Its all correct.  The install is broken.  We moved it up as top priority to fix.  Sorry, we haven’t had a fresh install for over a year.  Its been upgrades after our first install.

--- vr, Frank
