### ISSUE TITLE
fresh install error.  please see below.  Please see instructions on readme and make adjustments so a clean install works

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSend#272]
on new install, there is this error

PDOException: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'prev_assign' in /var/www/html/mSend/install/index.php:32 Stack trace: #0 /var/www/html/mSend/install/index.php(32): PDOStatement->execute(Array) #1 /var/www/html/mSend/install/index.php(109): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint in /var/www/html/mSend/install/index.php:32 Stack trace: #0 /var/www/html/mSend/install/index.php(32): PDOStatement->execute(Array) #1 /var/www/html/mSend/install/index.php(109): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint in /var/www/html/mSend/install/index.php:32 Stack trace: #0 /var/www/html/mSend/install/index.php(32): PDOStatement->execute(Array) #1 /var/www/html/mSend/install/index.php(109): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint in /var/www/html/mSend/install/index.php:32 Stack trace: #0 /var/www/html/mSend/install/index.php(32): PDOStatement->execute(Array) #1 /var/www/html/mSend/install/index.php(109): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint in /var/www/html/mSend/install/index.php:32 Stack trace: #0 /var/www/html/mSend/install/index.php(32): PDOStatement->execute(Array) #1 /var/www/html/mSend/install/index.php(109): try_query(Array) #2 {

**Comment by bluenevus** [comment]
I think its this

change in /install/database.php
line 26:
'expiry_date' TIMESTAMP NOT NULL DEFAULT '2038-01-18 22:00:00'

0000-00-00-00:00:00 is not in range of timestamp -_-"

**Comment by bluenevus** [comment]
It looks like they addressed it in code here.  Not sure it applies but we need this fixed

https://github.com/projectsend/projectsend/commit/d469ea3c980619522b4e3c0f48cfa903a5ab09d5

**Comment by bluenevus** [comment]
The user reported the he went to
mSend/install/database.php
39. prev_assign ENUM('0','1') NOT NULL DEFAULT '0',
40. prev_assign ENUM('0','1') NOT NULL DEFAULT '0',
and have removed line 40 and tried installing... it got installed successfully. But the front login page is not working! I can see only blank page.  Not sure if that helps but it sounds more like the system uri wasn't set

**Comment by cloudwaves** [comment]
is this issue fixed? I tried clean install from scratch, but now the install is working and login page is broken! only blank page is appearing.

**Comment by bluenevus** [comment]
Sorry, meant to contact you.  We fixed the database install issues.  Working on the login page issue.

--- vr, Frank

**Comment by cloudwaves** [comment]
I'm curious about this to use mSend! do you have any ETA to fix this?

**Comment by bluenevus** [comment]
Team is working on it.  Trying to replicate this issue.

Are you on centos 7?  Is it a bare install, virtual machine?



--- vr, Frank

**Comment by cloudwaves** [comment]
No, I use Amazon Linux 64 fresh install.

**Comment by bluenevus** [comment]
They are working on it.

--- vr, Frank

**Comment by bluenevus** [comment]
Did you  chown -R apache:apache *

to the mSend directory?

--- vr, Frank

**Comment by cloudwaves** [comment]
yeah... I use apacheuser instead of apache!
so it would be chown -R apacheuser:apache /var/www/html/mSend/*
chown -R apacheuser:apache /var/www/html/mSend
chmod -R 755 /var/html/mSend/*

**Comment by bluenevus** [comment]
You are right on the money so there are no permission issues with apache server.

I have the team working on the blank page issue.  I think we had this a year or so ago on this too.

--- vr, Frank

**Comment by bluenevus** [comment]
Attached is a sample workflow

Where it says projectsend uri.  Are you sure you have that correct for your hosting?

--- vr, Frank

**Comment by cloudwaves** [comment]
I don't see any attachment! 
I'm pretty sure I am using the correct URI as the actual projectsend is working fine in another instance...

**Comment by bluenevus** [comment]
Attaching it again.  If it doesn’t make it, github is stripping it.  Send me your email because for cloudwaves all I have is notifications@github.com<mailto:notifications@github.com> as your addy

--- vr, Frank

**Comment by cloudwaves** [comment]
you can send it to "cloudgprabhu @ gmail.com"

**Comment by cloudwaves** [comment]
where are you able to send it  the attachment? and is clean install working for you?

**Comment by bluenevus** [comment]
The developers did a clean install and confirmed it worked

--- vr, Frank

**Comment by cloudwaves** [comment]
This seems to be the issue with the php version... the install document is mentioned php7.2 but mSend is working on 7.1 on AWS Amazon Linux 64bit.

Now I can able to see the login page but unable to login with the credential. 
ERROR:
PHP Warning:  session_start(): Failed to read session data: files (path: /var/lib/php/7.1/session) in /var/www/html/mSend/sys.vars.php on line 12, referer: http://IPADDRESS/mSend/index.php

**Comment by cloudwaves** [comment]
Document to fresh install mSend in **AWS Amazon 64bit**
# Remove current apache & php 
sudo yum remove httpd* php*

# Install Apache 2.4
sudo yum install httpd24

# Install PHP 7.1
sudo yum install php71

# Install additional commonly used php packages
sudo yum install php71-gd php71-imap php71-mbstring php71-mysqlnd php71-opcache php71-pdo php71-pecl-apcu php71-fpm php71-json php71-xmlrpc php71-mcrypt 

# Install MYSQL
sudo yum install mysql56-server

#Start HTTP & MYSQL
sudo service httpd start
sudo service mysqld start

#Start HTTP & MYSQL at boot
sudo chkconfig httpd on
sudo chkconfig mysqld on

#MYSQL set password
sudo mysql_secure_installation

#Login MYSQL
mysql -u root -p mysql

#Create mysql database and user
create database DBNAME CHARACTER SET utf8 COLLATE utf8_general_ci;
create user 'USERNAME'@'localhost' identified by 'PASSWORD';
grant all privileges on *.* to 'USERNAME'@'localhost';
flush privileges;

#Directory permission
1.Add your user (in this case, ec2-user) to the apache group.
sudo usermod -a -G apache ec2-user
2.Log out and then log back in again
exit
3.Verify
groups
**OUTPUT**:ec2-user wheel apache
Change the group ownership and permission of /var/www
sudo chown -R ec2-user:apache /var/www
sudo chmod 2775 /var/www
