### ISSUE TITLE
Will more options display for the actions drop-down select dependent upon circumstances? If not, then why a drop-down for Delete?

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSend#28]
Screenshot Example

![sendfile_selected_file_action](https://user-images.githubusercontent.com/11938477/42056033-04701f70-7ae7-11e8-8206-c3336fbfdc3c.jpg)

**Comment by bluenevus** [comment]
Yes, in the future

--- vr, Frank
