### ISSUE TITLE
Login for office 365 doesn't work.  it always goes to msend url even though its configured for send in microsoft

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSend#3]
Office365 login doesn’t work.  For some reason it keeps going to the msend url vs what is set in the system.

![msoffice_login](https://user-images.githubusercontent.com/11938477/38877131-010407e6-422c-11e8-8e42-80bb56cb2001.jpg)

**Comment by ranjitpillai** [comment]
Fixed that. hardcoded msend url to base url.  Please check that.

**Comment by bluenevus** [comment]
clicking the button for office 365 doesn't do anything.  nothing pops up now

**Comment by bluenevus** [comment]
the link address for the button is this https://send.microhealthllc.com/index.php# which is the home page.  button doesn't do anything
