### ISSUE TITLE
Unable to install > Incorrect table definition

### ISSUE THREAD

**Issue by BenoitPoulet** [MicroHealthLLC/mSend#320]
Hello,
Error during install, after filling the admin info : 

There seems to be an error. Please try again.

exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1293 Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause' in /var/www/html/mSend-master/install/index.php:32 Stack trace: #0 /var/www/html/mSend-master/install/index.php(32): PDOStatement->execute(Array) #1 /var/www/html/mSend-master/install/index.php(109): try_query(Array) #2 {main}
exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1005 Can't create table 'mSend.tbl_files_relations' (errno: 150)' in /var/www/html/mSend-master/install/index.php:32 Stack trace: #0 /var/www/html/mSend-master/install/index.php(32): PDOStatement->execute(Array) #1 /var/www/html/mSend-master/install/index.php(109): try_query(Array) #2 {main}
exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1005 Can't create table 'mSend.tbl_notifications' (errno: 150)' in /var/www/html/mSend-master/install/index.php:32 Stack trace: #0 /var/www/html/mSend-master/install/index.php(32): PDOStatement->execute(Array) #1 /var/www/html/mSend-master/install/index.php(109): try_query(Array) #2 {main}
exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1005 Can't create table 'mSend.tbl_downloads' (errno: 150)' in /var/www/html/mSend-master/install/index.php:32 Stack trace: #0 /var/www/html/mSend-master/install/index.php(32): PDOStatement->execute(Array) #1 /var/www/html/mSend-master/install/index.php(109): try_query(Array) #2 {main}
exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1005 Can't create table 'mSend.tbl_categories_relations' (errno: 150)' in /var/www/html/mSend-master/install/index.php:32 Stack trace: #0 /var/www/html/mSend-master/install/index.php(32): PDOStatement->execute(Array) #1 /var/www/html/mSend-master/install/index.php(109): try_query(Array) #2 {main}

**Comment by bluenevus** [comment]
You need to use mysql greater than 5.5 or mariadb 10.1.  I have instructions on using mariadb 10.1.

When you uninstall the current version of mysql, don’t forget to drop the database then install mariadb 10.1 or mysql 5.6 or 5.7

--- vr, Frank

**Comment by BenoitPoulet** [comment]
Hello,

Thanks it's working with MariaDB 10. My bad.
