### ISSUE TITLE
Fix vertical responsive view breakpoint on Calendar View screen to avoid overlap

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSend#35]
Screenshot Example

![fix_calendar_view_responsive_breakpoint](https://user-images.githubusercontent.com/11938477/42108513-c2b791ea-7ba8-11e8-9007-3194c5641071.jpg)

**Comment by bluenevus** [comment]
Calendar view should be just that…a calendar view like this NOT a date picker

[cid:image001.png@01D40FB5.C4483230]


--- vr, Frank
