### ISSUE TITLE
Add Client form: Upload profile pic has class required, but does not get validated

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSend#361]
Screenshot Example

![add_client_profile_pic_not_validated](https://user-images.githubusercontent.com/11938477/55412563-b207e400-5535-11e9-9acf-a9d74706e0de.jpg)

**Comment by LAlexMHllc** [comment]
Was able to upload SVG even though that format is not supposed to be allowed

**Comment by bluenevus** [comment]
Its configured to allow all right now.  You have to change the setting to limit by file types

 

--- vr, Frank

**Comment by LAlexMHllc** [comment]
Use same file types allowed by Edit Client form.
