### ISSUE TITLE
can't upload file larger than 1mb results in image below

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSend#38]
![image](https://user-images.githubusercontent.com/3675043/42359543-7139d334-80b0-11e8-8c0f-35b86aa5f9bc.png)

**Comment by LAlexMHllc** [comment]
Was able to upload file approx 2mb. Updated code fixed issue?

![sent_2mb_file](https://user-images.githubusercontent.com/11938477/42462101-45c4b350-8370-11e8-8555-2a1ce9d88843.jpg)
