### ISSUE TITLE
missing drafts folder after inbox

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSend#39]
If I upload a file then don't send it...it goes to orphan files and while it is orphaned, there should be a folder called Drafts which are those file the user uploaded but didn't send so they can go back and finish this or delete it

![screenshot 2018-07-06 at 4 24 52 am](https://user-images.githubusercontent.com/3675043/42368356-d4f05d2a-80d4-11e8-84f3-f46117bbcc0d.png)

**Comment by LAlexMHllc** [comment]
Also include files uploaded via Send File screen (Upload files heading; upload-from-computer.php) that are not assigned. Presently, these files are listed under Admin - Manage Files.
