### ISSUE TITLE
updating client information results in this error even though no image was uploaded

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSend#4]
![screenshot 2018-04-17 at 5 30 32 pm](https://user-images.githubusercontent.com/3675043/38899262-5557a5a8-4265-11e8-8f64-e4f9add01fc4.png)

**Comment by ranjitpillai** [comment]
Profile pic upload is not a mandatory field. So if you didn't upload the file, it will not abort the form submission. Instead, it will show a warning message after client success message "File is not an image.Sorry, only JPG, JPEG, PNG & GIF files are allowed.Sorry, your file was not uploaded"
