### ISSUE TITLE
missing the full url link when generating a public download link

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSend#41]
![screenshot 2018-07-06 at 8 44 37 am](https://user-images.githubusercontent.com/3675043/42379546-f687a348-80f8-11e8-9ee6-d9078a96066b.png)

**Comment by LAlexMHllc** [comment]
Click the Public button from the Sent Files screen or Admin - Manage Files screen instead of the Sent Items screen (just lets you know files uploaded correctly).
