### ISSUE TITLE
Logged in user should be able to check/uncheck "Notify new uploads by e-mail" on their My Account screen and the value should stick.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSend#455]

**Comment by bluenevus** [comment]
By default it has to be checked. But they can choose to uncheck or recheck it

 

--- vr, Frank

**Comment by LAlexMHllc** [comment]
When user checks/unchecks "Notify new uploads by e-mail" then clicks "Update account" the form input should stick. Receive successful edit message, but the input does not stick, so the user still will not receive email UNLESS another user checks it for them. This needs to be fixed.

Screenshot Example of issue

![my_account_for_user_notify_upload_email_does_not_stick](https://user-images.githubusercontent.com/11938477/56975816-96492b00-6b3f-11e9-929e-3081e7a272b2.jpg)
