### ISSUE TITLE
logo size configuration doesn't work

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSend#5]
I set the size here
![image](https://user-images.githubusercontent.com/3675043/38934706-674d4f80-42ea-11e8-9f60-fc2c16c931e7.png)

however, it still remains the same size here

![image](https://user-images.githubusercontent.com/3675043/38934679-59b0ad72-42ea-11e8-883c-fe44954de48a.png)

**Comment by ranjitpillai** [comment]
Fixed. Please check.

**Comment by bluenevus** [comment]
Its even worse now
![image](https://user-images.githubusercontent.com/3675043/39002773-4a695a34-43c7-11e8-9e2c-b9e599fd9244.png)

no logo at all even after trying to re-upload

**Comment by bluenevus** [comment]
works
