### ISSUE TITLE
Client can not view file in Inbox after logging in. Sidebar menu should display with subfolders shown under Files.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSend#560]

**Comment by bluenevus** [comment]
this is a significant issue ranjit.  its the whole purpose of the system.  I sent a file and in the client form, I invited a new user.  that person logged in and saw no files.  couldn't open the tree either.  it should have gone straight to the inbox.  He was using edge.  could that be the issue?  I checked and he did indeed register to pick up the files and he is in the system and can login.

**Comment by bluenevus** [comment]
turns out this issue is related to the use of Edge browser.  I'm closing this as edge just sucks all the way around
