### ISSUE TITLE
Guest Drop-Off Summary - Remove "zip" from File Extensions Allowed; check to make sure "zip" is not included when "Submit Upload" clicked.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSend#670]
"zip" should not be allowed for Guest dropoff, because of batch upload. 

Screenshot Example

![zip_not_allowed_guest_dropoff](https://user-images.githubusercontent.com/11938477/70460250-df713e00-1a83-11ea-9955-f23a5e976a86.jpg)

**Comment by bluenevus** [comment]
Can you zip a zip?  Like include multiple files that includes one of them as a zip?  If so, then yes right?

 

--- vr, Frank

**Comment by LAlexMHllc** [comment]
Nested zips caused corrupt download file issues during testing. If this was not an issue for you and others, then please close this issue.
