### ISSUE TITLE
upload-process-dropoff-form.php - Don't need to display the Status, Assignations, Public, and Actions.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSend#679]
Screenshot Example for USER

![upload-processs-form-dropoff__items_to_not_display](https://user-images.githubusercontent.com/11938477/72276859-ddf4e180-35fe-11ea-80bb-aefa23687df6.jpg)

Screenshot Example for CLIENT

![upload-processs-form-dropoff__items_to_not_display_client](https://user-images.githubusercontent.com/11938477/72277170-7ab77f00-35ff-11ea-8a59-ed4dcebcf834.jpg)

**Comment by bluenevus** [comment]
I thought the edit was supposed to allow the user to send the same file to someone else.  Why is it disabled unless expired and deleted

 

Edit probably isn’t the right word as much as it is Resend

 

And resend is active if the file is still in the system and not deleted

 

--- vr, Frank

**Comment by LAlexMHllc** [comment]
Not for Requested Files
