### ISSUE TITLE
Allow user to upload multiple files but show it in one container, so they can send the batch to an individual rather than having separate containers for each file

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSend#68]
When someone uploads multiple files, it creates separate containers for each file.  However they are uploading multiple files to send to one individual.  This creates the situation where a user has to zip docs to send it.  Instead it should list the multiple files in the one container so they can send the multiple files they uploaded in one batch below description

![image](https://user-images.githubusercontent.com/3675043/42887014-f905ae34-8a72-11e8-98ab-04c011381513.png)

**Comment by LAlexMHllc** [comment]
When the "Upload Batch" button is clicked on the Upload file screen (see Issue #237), all the files will display in one container. The File information will have a Title and Description for each file, and Send To, Expiration date, Public downloading, Categories, and Future Send Date will be used for each file.

Screenshot Example

![send_form_batch](https://user-images.githubusercontent.com/11938477/50777161-d1f67700-1268-11e9-8059-473afc7b6998.jpg)
