### ISSUE TITLE
Email notifications are not working

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSend#7]
I tried the gmail option, I tried the sendmail option but neither sends an email notification

![image](https://user-images.githubusercontent.com/3675043/38945466-920598bc-4304-11e8-89d5-85379e1e1070.png)

**Comment by bluenevus** [comment]
still no email notifications

**Comment by ranjitpillai** [comment]
SMTP options that you have provided are for Gmail.  To know your SMTP option, you have to log to your Webmail. Gmail mailer is working fine I tested with my Gmail account I got the email notification. Please let me know if you're facing any issues.

**Comment by bluenevus** [comment]
It looks like when you send a file to a person who has yet to register, the default notification is NO.  the problem with that is that people are sending a file to a person and they have to get notified so that they will register as they are sending a file to them.  Though the workflow is correct in terms of an account created but not enabled until the user enables,the workflow is incorrect in that it sets the flag to notify no.  as a result,  that is why notifications haven’t been working I suspect
