### ISSUE TITLE
Inbox Files - after user signs signature request document, remove file from Inbox. If this will cause issues, then remove Title link so Unauthorized screen will not display onclick.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSend#716]
Screenshot Example

![inbox_file_remove_title_link_signed_signature_file_avoid_unauthorized_access](https://user-images.githubusercontent.com/11938477/88098844-67660d00-cb68-11ea-94c4-6130c2f1925f.png)

**Comment by bluenevus** [comment]
after its signed, it has to be removed from the inbox.  its just way to confusing.  Its in sent where it should be and they can download what they sent so there is no reason to have it still in the inbox after its already been signed and sent

**Comment by LAlexMHllc** [comment]
The Inbox Title link was removed from the Inbox screen for the receiver of the signed file (INCORRECT).
Should have been removed from the Inbox screen of the signee to avoid the error screen onclick.

**Comment by LAlexMHllc** [comment]
Signed requested file in Inbox for Client link was removed, but not requested file link in Inbox for system user.
