### ISSUE TITLE
Manage Files - remove Title link and Edit link for all files

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSend#717]

**Comment by bluenevus** [comment]
There really should be no links in manage files as those are private to the sender and reciever.

Frank Tucker
Chief Executive Officer, Executive Office
t: 855-294-3547
m: 571-327-1211
frank.tucker@microhealthllc.com | www.microhealthllc.com
8229 Boone Blvd ​Ste 500, ​Vienna, VA 22182
This communication and attachments may contain confidential, proprietary or privileged information for only the intended recipient. If you are not the intended recipient, disclosing, distributing, copying, or using this communication is strictly prohibited. If you received this message in error, please notify the sender immediately by return email and delete it from your system.
