### ISSUE TITLE
create_signature_spot.php  - fails with error 500

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSend#728]

**Comment by bluenevus** [comment]
![image](https://user-images.githubusercontent.com/3675043/89065030-06dd8980-d339-11ea-84ec-405ee81decc7.png)

**Comment by bluenevus** [comment]
![image](https://user-images.githubusercontent.com/3675043/89066563-b0be1580-d33b-11ea-9afe-2eb6004442fc.png)

**Comment by bluenevus** [comment]
also, php70u-gd was made obsolete by  php-gd.  That is what is installed and what the repos support.  So if you are running the legacy 70u that may be the issue and we can't have something no longer supported on the system when its been replaced by another library
![image](https://user-images.githubusercontent.com/3675043/89067374-270f4780-d33d-11ea-850d-d1a680c0c9e2.png)
