### ISSUE TITLE
upload-process-form.php - Sent Items form: remove "Add all" button from Sent To and Categories.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSend#761]
Screenshot Example

![upload_from_computer_remove_add_all_buttons](https://user-images.githubusercontent.com/11938477/90416854-02c3a280-e081-11ea-875f-921be93a5733.png)

**Comment by bluenevus** [comment]
Just remove the Add All button for now.  You can leave the groups for now

**Comment by bluenevus** [comment]
same with categories, remove the add all button
