### ISSUE TITLE
Upload Files and Dropoff - should be batch upload.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mSend#764]
Should have been batch upload, not individual files.

Screenshot Example

![upload_multi_files](https://user-images.githubusercontent.com/11938477/90548846-95387480-e15b-11ea-844a-078e56448efb.png)

![upload_files_should_be_batch_upload](https://user-images.githubusercontent.com/11938477/90548864-99649200-e15b-11ea-90b2-2305c712ffa8.png)

**Comment by bluenevus** [comment]
Whether its one file or a bunch of files, its always a batch upload and zipped.
