### ISSUE TITLE
Public Files Download Corrupted 

### ISSUE THREAD

**Issue by mark-sellars** [MicroHealthLLC/mSend#771]
Sorry I got one more that I am stumped on. 

When I send a file as public it downloads corrupted. This happens either with the link or as a registered user also as the user who uploaded the file.

**Comment by LAlexMHllc** [comment]
NOTE: File downloaded by clicking the Title link is not corrupted. The file downloaded using Public URL is corrupted.

**Comment by LAlexMHllc** [comment]
Need to decrypt file

**Comment by LAlexMHllc** [comment]
Screenshot of Public file downloaded using Public URL (needs to be decrypted)

![download_file_from_Public_URL_needs_to_be_decrypted](https://user-images.githubusercontent.com/11938477/92013491-ddd75c80-ed1b-11ea-8008-ba267cccaf69.png)

VS

Screenshot of Public file downloaded using Title link

![download_file_from_Public_Title_link_gets_decrypted](https://user-images.githubusercontent.com/11938477/92013504-e3cd3d80-ed1b-11ea-9e03-3745d5a5e880.png)
