### ISSUE TITLE
I resent an expired file in my sent folder and it said it successfully sent then disappeared from the list

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSend#85]
![image](https://user-images.githubusercontent.com/3675043/43970865-f983542e-9c9c-11e8-98e3-e23b9006da4d.png)

Since I resent it...it should be in the sent folder with the updated information that I did but instead...it simply went missing from the sent folder

**Comment by LAlexMHllc** [comment]
Closed Issue #43 should prevent this
