### ISSUE TITLE
cant return back from send screen to sent box

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mSend#9]
I first went here to edit the sent file
![image](https://user-images.githubusercontent.com/3675043/38999074-f9ef067e-43be-11e8-9981-7395e322eb78.png)

clicked this
![image](https://user-images.githubusercontent.com/3675043/38999085-022cddde-43bf-11e8-9a9c-e87d66e5af7d.png)

clicked continue and the screen simply refreshed.  nothing sent, nothing done.  nothing happened

**Comment by ranjitpillai** [comment]
This functionality also working fine for me. You can check the below link.
https://demo4.rndshosting.com/msend_live_new/
username : rjpdev
password: 12345678

**Comment by bluenevus** [comment]
this is still an issue.

**Comment by bluenevus** [comment]
sent you an email regarding this
